fix: sensitive config, store secrets encrypted
nextcloud/integration_notion pull request #51
Opened 2024-10-22 19:04 UTC by andrey18106

Encrypt token, client_id and client_secret values.

2024-10-23 08:33 UTC, julien-nc requested changes

2024-10-23 08:33 UTC, julien-nc commented on lib/Controller/ConfigController.php
> +		$clientSecret = $this->crypto->decrypt($this->config->getAppValue(Application::APP_ID, 'client_secret'));
This will crash when trying to decrypt an empty string. Same for encrypt.
You can either avoid encrypting/decrypting empty strings: https://github.com/nextcloud/integration_github/blob/main/lib/Service/SecretService.php#L63-L83

Or you can bump min NC to 29 and use IAppConfig like in integration_openai.
To store and encrypt: https://github.com/nextcloud/integration_openai/blob/main/lib/Service/OpenAiSettingsService.php#L357 The 5th param of `setValueString` is a flag to store the value as "sensitive". Sensitive values are encrypted.
To get the value (encrypted or not): https://github.com/nextcloud/integration_openai/blob/main/lib/Service/OpenAiSettingsService.php#L79 . Sensitive values are automatically decrypted.

2024-10-23 08:33 UTC, julien-nc commented on lib/Controller/ConfigController.php
> +			if (in_array($key, ['token'])) {
```suggestion
			if (in_array($key, ['token']) && $value !== '') {
```

2024-10-23 08:33 UTC, julien-nc commented on lib/Controller/ConfigController.php
> +			}
Not needed as you exit this method if the key is client_id or client_secret.

2024-10-23 08:33 UTC, julien-nc commented on lib/Controller/ConfigController.php
> +			}
```suggestion
			if (in_array($key, ['client_id', 'client_secret']) && $value !== '') {
				$value = $this->crypto->encrypt($value);
			}
```

2024-10-23 08:33 UTC, julien-nc commented on lib/Controller/ConfigController.php
> +		$clientID = $this->crypto->decrypt($this->config->getAppValue(Application::APP_ID, 'client_id'));
If you don't go with IAppConfig, here is how to safely decrypt:
```suggestion
		$clientID = $this->config->getAppValue(Application::APP_ID, 'client_id');
		$clientID = $clientID === '' ? '' : $this->crypto->decrypt($clientID);
```

2024-10-23 08:33 UTC, julien-nc commented on lib/Controller/ConfigController.php
> +				$accessToken = $this->crypto->encrypt($result['access_token']);
If you don't go with IAppConfig, here is how to safely encrypt:
```suggestion
				$accessToken = $result['access_token'];
				$accessToken = $accessToken === '' ? '' : $this->crypto->encrypt($accessToken);
```

2024-10-23 08:33 UTC, julien-nc commented on lib/Migration/Version1200Date202410151354.php
> +		foreach (['appconfig', 'preferences'] as $tableToUpdate) {
As the client_id and client_secret are only stored once in oc_appconfig, you can simply read it with IConfig (or IAppConfig if you switch to it) and write it again encrypted.

It will also simplify the logic of the part dealing with oc_preferences.

2024-10-23 11:50 UTC, andrey18106 commented on lib/Controller/ConfigController.php
> +		$clientSecret = $this->crypto->decrypt($this->config->getAppValue(Application::APP_ID, 'client_secret'));
Thank you for pointing on this, I think we shouldn't bump NC version, but just check for empty string is enough.

2024-10-23 13:52 UTC, julien-nc requested changes

2024-10-23 13:52 UTC, julien-nc commented on lib/Migration/Version1200Date202410151354.php
> +		$qbSelect->andWhere($or);
```suggestion
		$qbSelect->andWhere(
		    $qbSelect->expr()->eq('configkey', $qbSelect->createNamedParameter('token', IQueryBuilder::PARAM_STR))
		);
```

2024-10-23 13:52 UTC, julien-nc commented on lib/Search/NotionSearchDatabasesProvider.php
> +		$accessToken = $this->crypto->decrypt($this->config->getUserValue($user->getUID(), Application::APP_ID, 'token'));
Missing empty string check.

2024-10-23 13:52 UTC, julien-nc commented on lib/Search/NotionSearchPagesProvider.php
> +		$accessToken = $this->crypto->decrypt($this->config->getUserValue($user->getUID(), Application::APP_ID, 'token'));
Missing empty string check.

2024-10-23 13:52 UTC, julien-nc commented on lib/Service/NotionAPIService.php
> +		$accessToken = $this->crypto->decrypt($this->config->getUserValue($userId, Application::APP_ID, 'token'));
Missing empty string check.

2024-10-24 10:30 UTC, julien-nc commented
I hope you don't mind that I added a commit in there to check the access token before encrypting it.

2024-10-24 10:30 UTC, julien-nc approved these changes

2024-10-24 10:30 UTC, merged

2024-11-03 09:20 UTC, bigcat88 commented
Do not publish version with this, you missed encryption of `access_token` in Migration file